import type { ReportDefinitionContract } from '../types/reporting-types';

export const CORE_REPORT_DEFINITIONS: ReportDefinitionContract[] = [
  // -------------------------------------------------------------------------
  // Student Reports (4)
  // -------------------------------------------------------------------------
  {
    key: 'student.credentials',
    domain: 'Student',
    version: 1,
    title: 'État d\'Activation des Comptes Élèves',
    description: 'Rapport d\'activation et de préparation des comptes élèves (sans secrets ni mots de passe).',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'StudentAdapter.getCredentialStatusReport',
    parametersSchema: [
      { key: 'status', label: 'Statut du Compte', type: 'select', options: [{ label: 'Tous', value: 'all' }, { label: 'Actif', value: 'active' }, { label: 'Inactif', value: 'inactive' }] },
    ],
    columnsSchema: [
      { key: 'studentId', label: 'ID Élève', type: 'string' },
      { key: 'fullName', label: 'Nom Complet', type: 'string' },
      { key: 'role', label: 'Rôle', type: 'string' },
      { key: 'maskedEmail', label: 'Email (Masqué)', type: 'string' },
      { key: 'isProvisioned', label: 'Compte Créé', type: 'boolean' },
      { key: 'lastLoginAt', label: 'Dernière Connexion', type: 'datetime' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['students.read'],
    isActive: true,
  },
  {
    key: 'student.admission_funnel',
    domain: 'Student',
    version: 1,
    title: 'Entonnoir de Conversion des Admissions',
    description: 'Analyse du flux des prospects de la demande d\'information jusqu\'à l\'inscription finale.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'StudentAdapter.getAdmissionFunnelReport',
    parametersSchema: [
      { key: 'startDate', label: 'Date Début', type: 'date' },
      { key: 'endDate', label: 'Date Fin', type: 'date' },
    ],
    columnsSchema: [
      { key: 'stage', label: 'Étape du Funnel', type: 'string' },
      { key: 'count', label: 'Nombre d\'Inscrits', type: 'number' },
      { key: 'conversionRate', label: 'Taux de Conversion (%)', type: 'percentage' },
      { key: 'avgProcessingDays', label: 'Temps Moyen (Jours)', type: 'number' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['admissions.view', 'students.read'],
    isActive: true,
  },
  {
    key: 'student.class_section_occupancy',
    domain: 'Student',
    version: 1,
    title: 'Taux d\'Occupation des Classes & Sections',
    description: 'Rapport d\'effectifs et de capacité d\'accueil par classe, section et cycle.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'StudentAdapter.getClassSectionOccupancyReport',
    parametersSchema: [
      { key: 'classId', label: 'Classe', type: 'string' },
    ],
    columnsSchema: [
      { key: 'className', label: 'Classe', type: 'string' },
      { key: 'sectionName', label: 'Section', type: 'string' },
      { key: 'enrolledCount', label: 'Inscrits', type: 'number' },
      { key: 'capacity', label: 'Capacité Max', type: 'number' },
      { key: 'occupancyRate', label: 'Taux d\'Occupation (%)', type: 'percentage' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['academics.read', 'students.read'],
    isActive: true,
  },
  {
    key: 'student.siblings',
    domain: 'Student',
    version: 1,
    title: 'Répartition par Foyer & Fratrie',
    description: 'Groupement des élèves par foyer familial et tuteur légal autorisé.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'StudentAdapter.getSiblingReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'householdId', label: 'ID Foyer', type: 'string' },
      { key: 'guardianName', label: 'Tuteur Principal', type: 'string' },
      { key: 'guardianPhone', label: 'Téléphone Tuteur', type: 'string' },
      { key: 'studentCount', label: 'Nombre d\'Enfants', type: 'number' },
      { key: 'studentNames', label: 'Élèves associés', type: 'string' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['guardians.read', 'students.read'],
    isActive: true,
  },

  // -------------------------------------------------------------------------
  // Fees Reports (4)
  // -------------------------------------------------------------------------
  {
    key: 'fees.summary',
    domain: 'Fees',
    version: 1,
    title: 'Récapitulatif Global des Frais Scolaires',
    description: 'Synthèse des factures émises, remises, paiements perçus et soldes dus.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'FeesAdapter.getFeesSummaryReport',
    parametersSchema: [
      { key: 'status', label: 'Statut Facture', type: 'select', options: [{ label: 'Tous', value: 'all' }, { label: 'Payée', value: 'paid' }, { label: 'Partielle', value: 'partial' }, { label: 'En attente', value: 'pending' }] },
    ],
    columnsSchema: [
      { key: 'invoiceNumber', label: 'N° Facture', type: 'string' },
      { key: 'studentName', label: 'Élève', type: 'string' },
      { key: 'totalAmount', label: 'Montant Total', type: 'currency' },
      { key: 'discountAmount', label: 'Remise', type: 'currency' },
      { key: 'paidAmount', label: 'Réglé', type: 'currency' },
      { key: 'outstandingAmount', label: 'Reste à Payer', type: 'currency' },
      { key: 'status', label: 'Statut', type: 'badge' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },
  {
    key: 'fees.receipts',
    domain: 'Fees',
    version: 1,
    title: 'Journal des Reçus de Caisse',
    description: 'Liste des encaissements enregistrés par session de caisse, mode de règlement et caissier.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'FeesAdapter.getReceiptsReport',
    parametersSchema: [
      { key: 'method', label: 'Mode de Paiement', type: 'select', options: [{ label: 'Tous', value: 'all' }, { label: 'Espèces', value: 'cash' }, { label: 'Carte', value: 'card' }, { label: 'Chèque', value: 'check' }, { label: 'Virement', value: 'transfer' }] },
    ],
    columnsSchema: [
      { key: 'receiptNumber', label: 'N° Reçu', type: 'string' },
      { key: 'paymentDate', label: 'Date Règlement', type: 'datetime' },
      { key: 'cashierName', label: 'Caissier', type: 'string' },
      { key: 'paymentMethod', label: 'Mode', type: 'string' },
      { key: 'amount', label: 'Montant Encassé', type: 'currency' },
      { key: 'isReversed', label: 'Annulé/Remboursé', type: 'boolean' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },
  {
    key: 'fees.due_aging',
    domain: 'Fees',
    version: 1,
    title: 'Balance Âgée des Impayés (Recouvrement)',
    description: 'Analyse de l\'ancienneté des créances échues (Courant, 1-30, 31-60, 61-90, 90+ jours).',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'FeesAdapter.getDueAgingReport',
    parametersSchema: [
      { key: 'asOfDate', label: 'Arrêté au', type: 'date' },
    ],
    columnsSchema: [
      { key: 'studentName', label: 'Élève', type: 'string' },
      { key: 'guardianContact', label: 'Contact Tuteur', type: 'string' },
      { key: 'currentAmount', label: 'Non Échu', type: 'currency' },
      { key: 'days1to30', label: '1 - 30 Jours', type: 'currency' },
      { key: 'days31to60', label: '31 - 60 Jours', type: 'currency' },
      { key: 'days61to90', label: '61 - 90 Jours', type: 'currency' },
      { key: 'days90Plus', label: '> 90 Jours', type: 'currency' },
      { key: 'totalBalance', label: 'Solde Total Dû', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },
  {
    key: 'fees.fines',
    domain: 'Fees',
    version: 1,
    title: 'Registre des Pénalités & Exonérations',
    description: 'Suivi des frais de retard appliqués, encaissés, exonérés ou annulés.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'FeesAdapter.getFinesReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'fineId', label: 'ID Pénalité', type: 'string' },
      { key: 'studentName', label: 'Élève', type: 'string' },
      { key: 'amount', label: 'Montant Pénalité', type: 'currency' },
      { key: 'reason', label: 'Motif', type: 'string' },
      { key: 'isWaived', label: 'Exonéré', type: 'boolean' },
      { key: 'waivedBy', label: 'Exonéré Par', type: 'string' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },

  // -------------------------------------------------------------------------
  // Financial Reports (5)
  // -------------------------------------------------------------------------
  {
    key: 'finance.statement',
    domain: 'Financial',
    version: 1,
    title: 'Relevé de Compte Tiers / Tuteur',
    description: 'Historique chronologique des débits, crédits et solde progressif d\'un compte.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'FinancialAdapter.getAccountStatementReport',
    parametersSchema: [
      { key: 'accountId', label: 'Compte', type: 'string', required: true },
      { key: 'startDate', label: 'Date Début', type: 'date' },
      { key: 'endDate', label: 'Date Fin', type: 'date' },
    ],
    columnsSchema: [
      { key: 'transactionDate', label: 'Date', type: 'date' },
      { key: 'voucherNumber', label: 'N° Pièce', type: 'string' },
      { key: 'description', label: 'Libellé', type: 'string' },
      { key: 'debit', label: 'Débit', type: 'currency' },
      { key: 'credit', label: 'Crédit', type: 'currency' },
      { key: 'runningBalance', label: 'Solde Progressif', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },
  {
    key: 'finance.income_expense',
    domain: 'Financial',
    version: 1,
    title: 'Compte de Produits et Charges (CPC)',
    description: 'Ventilation périodique des recettes de scolarité et des dépenses d\'exploitation.',
    sensitivityLevel: 'restricted',
    freshnessType: 'snapshot',
    executionAdapter: 'FinancialAdapter.getIncomeExpenseReport',
    parametersSchema: [
      { key: 'periodKey', label: 'Période Comptable', type: 'string' },
    ],
    columnsSchema: [
      { key: 'category', label: 'Catégorie', type: 'string' },
      { key: 'accountName', label: 'Poste Comptable', type: 'string' },
      { key: 'amount', label: 'Montant Total', type: 'currency' },
      { key: 'percentageOfTotal', label: '% du Total', type: 'percentage' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },
  {
    key: 'finance.transactions',
    domain: 'Financial',
    version: 1,
    title: 'Grand Livre / Journal des Écritures',
    description: 'Détail exhaustif des lignes de journal comptable validées.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'FinancialAdapter.getTransactionsReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'journalId', label: 'ID Écriture', type: 'string' },
      { key: 'entryDate', label: 'Date Écriture', type: 'date' },
      { key: 'accountCode', label: 'N° Compte', type: 'string' },
      { key: 'debitAmount', label: 'Débit', type: 'currency' },
      { key: 'creditAmount', label: 'Crédit', type: 'currency' },
      { key: 'status', label: 'Statut', type: 'badge' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },
  {
    key: 'finance.balance_sheet',
    domain: 'Financial',
    version: 1,
    title: 'Bilan Comptable (Actif = Passif + Capitaux)',
    description: 'État du patrimoine financier à la clôture de période (Actif = Passif + Capitaux Propres).',
    sensitivityLevel: 'restricted',
    freshnessType: 'snapshot',
    executionAdapter: 'FinancialAdapter.getBalanceSheetReport',
    parametersSchema: [
      { key: 'asOfDate', label: 'Date de Bilan', type: 'date' },
    ],
    columnsSchema: [
      { key: 'section', label: 'Classe de Bilan', type: 'string' },
      { key: 'item', label: 'Poste', type: 'string' },
      { key: 'amount', label: 'Montant Solde', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },
  {
    key: 'finance.income_vs_expense',
    domain: 'Financial',
    version: 1,
    title: 'Tendance Comparée Produits vs Charges',
    description: 'Évolution mensuelle des recettes encaissées par rapport aux dépenses payées.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'FinancialAdapter.getIncomeVsExpenseReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'month', label: 'Mois', type: 'string' },
      { key: 'totalIncome', label: 'Produits Encassés', type: 'currency' },
      { key: 'totalExpense', label: 'Charges Payées', type: 'currency' },
      { key: 'netResult', label: 'Résultat Net', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['finance.read'],
    isActive: true,
  },

  // -------------------------------------------------------------------------
  // Attendance Reports (5)
  // -------------------------------------------------------------------------
  {
    key: 'attendance.student_log',
    domain: 'Attendance',
    version: 1,
    title: 'Historique Détaillé des Présences Élève',
    description: 'Relevé individuel des séances, retards en minutes, justifications et motifs.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'AttendanceAdapter.getStudentAttendanceLogReport',
    parametersSchema: [
      { key: 'studentId', label: 'Élève', type: 'string' },
    ],
    columnsSchema: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'sessionName', label: 'Séance', type: 'string' },
      { key: 'status', label: 'Statut', type: 'badge' },
      { key: 'lateMinutes', label: 'Minutes de Retard', type: 'number' },
      { key: 'isExcused', label: 'Motif Justifié', type: 'boolean' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['attendance.read'],
    isActive: true,
  },
  {
    key: 'attendance.daily_matrix',
    domain: 'Attendance',
    version: 1,
    title: 'Matrice Journalière de Présence par Section',
    description: 'Grille d\'appel journalier par classe/section avec indicateur de registres verrouillés.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'AttendanceAdapter.getDailySectionMatrixReport',
    parametersSchema: [
      { key: 'date', label: 'Date d\'Appel', type: 'date' },
    ],
    columnsSchema: [
      { key: 'className', label: 'Classe', type: 'string' },
      { key: 'sectionName', label: 'Section', type: 'string' },
      { key: 'presentCount', label: 'Présents', type: 'number' },
      { key: 'absentCount', label: 'Absents', type: 'number' },
      { key: 'lateCount', label: 'En Retard', type: 'number' },
      { key: 'registerStatus', label: 'Appel Verrouillé', type: 'badge' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['attendance.read'],
    isActive: true,
  },
  {
    key: 'attendance.overview_streaks',
    domain: 'Attendance',
    version: 1,
    title: 'Synthèse d\'Assiduité & Alertes Récurrence',
    description: 'Statistiques globales de présence et identification des séries d\'absences injustifiées.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'AttendanceAdapter.getAttendanceOverviewReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'studentName', label: 'Élève', type: 'string' },
      { key: 'totalSessions', label: 'Séances Évaluées', type: 'number' },
      { key: 'attendanceRate', label: 'Taux de Présence (%)', type: 'percentage' },
      { key: 'unexcusedAbsences', label: 'Absences non Justifiées', type: 'number' },
      { key: 'riskAlertLevel', label: 'Niveau de Risque', type: 'badge' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['attendance.read'],
    isActive: true,
  },
  {
    key: 'attendance.employee_summary',
    domain: 'Attendance',
    version: 1,
    title: 'Pointage & Heures de Présence Personnel',
    description: 'Heures travaillées, retards et absences du personnel enseignant et administratif.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'AttendanceAdapter.getEmployeeAttendanceSummaryReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'employeeName', label: 'Employé', type: 'string' },
      { key: 'workedDays', label: 'Jours Présents', type: 'number' },
      { key: 'totalHours', label: 'Heures Effectuées', type: 'number' },
      { key: 'lateArrivals', label: 'Nombre de Retards', type: 'number' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['attendance.read'],
    isActive: true,
  },
  {
    key: 'attendance.exam_session',
    domain: 'Attendance',
    version: 1,
    title: 'Émargement des Séances d\'Examen',
    description: 'Présence, émargement et incidents des candidats en salle d\'examen.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'AttendanceAdapter.getExamSessionAttendanceReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'examName', label: 'Examen', type: 'string' },
      { key: 'candidateName', label: 'Candidat', type: 'string' },
      { key: 'seatNumber', label: 'N° Place', type: 'string' },
      { key: 'checkInStatus', label: 'Émargé', type: 'badge' },
      { key: 'incidentNote', label: 'Remarque / Incident', type: 'string' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['attendance.read', 'grading.read'],
    isActive: true,
  },

  // -------------------------------------------------------------------------
  // HR Reports (2)
  // -------------------------------------------------------------------------
  {
    key: 'hr.payroll_summary',
    domain: 'HR',
    version: 1,
    title: 'Masse Salariale & Synthèse de Paie',
    description: 'Synthèse des traitements bruts, cotisations et net à payer par département (avec masquage si < 3 personnes).',
    sensitivityLevel: 'confidential',
    freshnessType: 'snapshot',
    executionAdapter: 'HRAdapter.getPayrollSummaryReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'department', label: 'Département', type: 'string' },
      { key: 'headcount', label: 'Effectif', type: 'number' },
      { key: 'grossPay', label: 'Masse Brute (Masqué si < 3)', type: 'currency' },
      { key: 'netPay', label: 'Net à Payer (Masqué si < 3)', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['hr.read'],
    isActive: true,
  },
  {
    key: 'hr.leave_balances',
    domain: 'HR',
    version: 1,
    title: 'Droits & Soldes de Congés du Personnel',
    description: 'Compteur des jours de congés acquis, pris et solde restant par collaborateur.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'HRAdapter.getLeaveBalancesReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'employeeName', label: 'Employé', type: 'string' },
      { key: 'leaveType', label: 'Type de Congé', type: 'string' },
      { key: 'entitledDays', label: 'Droits Annuels', type: 'number' },
      { key: 'usedDays', label: 'Jours Pris', type: 'number' },
      { key: 'remainingDays', label: 'Solde Restant', type: 'number' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['hr.read'],
    isActive: true,
  },

  // -------------------------------------------------------------------------
  // Examination Reports (3)
  // -------------------------------------------------------------------------
  {
    key: 'exam.report_card',
    domain: 'Examination',
    version: 1,
    title: 'Bulletin Scolaire Officiel (Snapshot Examen)',
    description: 'Génération et archivage des bulletins de notes officiels validés.',
    sensitivityLevel: 'restricted',
    freshnessType: 'snapshot',
    executionAdapter: 'ExaminationAdapter.getReportCardSnapshotReport',
    parametersSchema: [
      { key: 'studentId', label: 'Élève', type: 'string' },
      { key: 'periodKey', label: 'Trimestre/Semestre', type: 'string' },
    ],
    columnsSchema: [
      { key: 'subjectName', label: 'Matière', type: 'string' },
      { key: 'score', label: 'Note / 20', type: 'number' },
      { key: 'classAverage', label: 'Moyenne Classe', type: 'number' },
      { key: 'teacherComment', label: 'Appréciation Enseignant', type: 'string' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['grading.read'],
    isActive: true,
  },
  {
    key: 'exam.tabulation_sheet',
    domain: 'Examination',
    version: 1,
    title: 'Procès-Verbal & Feuille de Tabulation des Notes',
    description: 'Tableau récapitulatif des notes par élève x matière pour conseil de classe.',
    sensitivityLevel: 'restricted',
    freshnessType: 'realtime',
    executionAdapter: 'ExaminationAdapter.getTabulationSheetReport',
    parametersSchema: [
      { key: 'classId', label: 'Classe', type: 'string' },
    ],
    columnsSchema: [
      { key: 'studentName', label: 'Élève', type: 'string' },
      { key: 'totalMarks', label: 'Total Général', type: 'number' },
      { key: 'overallAverage', label: 'Moyenne Générale', type: 'number' },
      { key: 'rank', label: 'Rang', type: 'number' },
      { key: 'decision', label: 'Décision du Conseil', type: 'string' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['grading.read'],
    isActive: true,
  },
  {
    key: 'exam.progress',
    domain: 'Examination',
    version: 1,
    title: 'Suivi de la Progression & Compétences',
    description: 'Analyse comparative des résultats d\'un élève au fil des périodes d\'évaluation.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'ExaminationAdapter.getProgressReport',
    parametersSchema: [
      { key: 'studentId', label: 'Élève', type: 'string' },
    ],
    columnsSchema: [
      { key: 'period', label: 'Période', type: 'string' },
      { key: 'averageScore', label: 'Moyenne Période', type: 'number' },
      { key: 'trendIndicator', label: 'Évolution', type: 'badge' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['grading.read'],
    isActive: true,
  },

  // -------------------------------------------------------------------------
  // Inventory Reports (4)
  // -------------------------------------------------------------------------
  {
    key: 'inventory.stock_valuation',
    domain: 'Inventory',
    version: 1,
    title: 'Inventaire & Valorisation des Stocks',
    description: 'Quantités en stock, seuils de réapprovisionnement et valeur financière des articles.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'InventoryAdapter.getStockValuationReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'itemCode', label: 'Code Article', type: 'string' },
      { key: 'itemName', label: 'Désignation', type: 'string' },
      { key: 'quantityOnHand', label: 'Qté en Stock', type: 'number' },
      { key: 'unitPrice', label: 'Prix Unitaire', type: 'currency' },
      { key: 'totalValuation', label: 'Valeur Stock', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['inventory.read'],
    isActive: true,
  },
  {
    key: 'inventory.purchase_summary',
    domain: 'Inventory',
    version: 1,
    title: 'Journal des Achats & Réceptions Fournisseurs',
    description: 'Commandes d\'achats d\'équipements et fournitures par fournisseur et statut.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'InventoryAdapter.getPurchaseSummaryReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'poNumber', label: 'N° Bon Commande', type: 'string' },
      { key: 'supplierName', label: 'Fournisseur', type: 'string' },
      { key: 'orderDate', label: 'Date Commande', type: 'date' },
      { key: 'totalAmount', label: 'Montant Total', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['inventory.read'],
    isActive: true,
  },
  {
    key: 'inventory.sales_revenue',
    domain: 'Inventory',
    version: 1,
    title: 'Ventes Boutique Scolaire & Manuels',
    description: 'Ventes d\'articles, fournitures et manuels scolaires à la boutique de l\'école.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'InventoryAdapter.getSalesRevenueReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'receiptNumber', label: 'N° Vente', type: 'string' },
      { key: 'customerName', label: 'Client / Élève', type: 'string' },
      { key: 'itemsCount', label: 'Qté Articles', type: 'number' },
      { key: 'totalRevenue', label: 'Recette Total', type: 'currency' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['inventory.read'],
    isActive: true,
  },
  {
    key: 'inventory.issues_custody',
    domain: 'Inventory',
    version: 1,
    title: 'Prêts d\'Équipements & Consommations',
    description: 'Matériel prêté au personnel/élèves, dates d\'échéance de retour et retards.',
    sensitivityLevel: 'standard',
    freshnessType: 'realtime',
    executionAdapter: 'InventoryAdapter.getIssuesCustodyReport',
    parametersSchema: [],
    columnsSchema: [
      { key: 'issueId', label: 'N° Prêt', type: 'string' },
      { key: 'borrowerName', label: 'Emprunteur', type: 'string' },
      { key: 'itemName', label: 'Matériel', type: 'string' },
      { key: 'issueDate', label: 'Date Prêt', type: 'date' },
      { key: 'dueDate', label: 'Échéance', type: 'date' },
      { key: 'isOverdue', label: 'En Retard', type: 'boolean' },
    ],
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    requiredPermissions: ['inventory.read'],
    isActive: true,
  },
];
