// BRANCH-SCOPE-01 B3-01: every API route -> its branch mode (plan section 5).
//
// Modes:
//   own      the row has its own branch_id            -> branchWhere(ctx, table.branchId)
//   student  the row belongs to a student             -> filter through the student's user.branchId
//   employee the row belongs to an employee           -> via employee_profiles.branchId or the employee's user.branchId
//   shared   tenant-wide configuration or legal books -> none; UI says "Commun à tous les sites"
//   personal self or relationship data                -> none
//   platform super-admin, public, health, webhooks    -> none
//
// review: true marks entries the prefill heuristics were NOT confident about;
// a wave (W1-W6) must resolve each one before scoping that route.
//
// Prefilled by script (scratch/bs-registry-gen.mjs) from the filesystem plus
// the module/table scan. scripts/check-branch-scope.ts enforces that this
// registry covers every route on the filesystem and that own/student/employee
// routes use the branch helpers (or are listed in
// scripts/branch-scope-baseline.json, which may only shrink).

export type BranchRouteMode = 'own' | 'student' | 'employee' | 'shared' | 'personal' | 'platform' | 'review';

export type BranchRouteEntry = {
  mode: BranchRouteMode;
  /** For own/student/employee: the column (or joined column) the branch
   *  filter keys on. One per module, decided in the registry — not per route. */
  column?: string;
  /** Heuristic prefill was unsure; the owning wave must resolve this. */
  review?: boolean;
};

export const BRANCH_SCOPE_REGISTRY: Record<string, BranchRouteEntry> = {
  '/api/academics/academic-years': { mode: 'shared' },
  '/api/academics/assessment-definitions': { mode: 'shared' },
  '/api/academics/assessment-definitions/[id]/publish': { mode: 'shared' },
  '/api/academics/assessment-plans': { mode: 'shared' },
  '/api/academics/assessment-sessions': { mode: 'shared' },
  '/api/academics/assignments': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/assignments/grade': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/assignments/submit': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/class-offerings': { mode: 'own', column: 'classes.branchId (via class_sections.classId)' },
  '/api/academics/class-offerings/copy': { mode: 'own', column: 'classes.branchId (via class_sections.classId)' },
  '/api/academics/class-results': { mode: 'shared' },
  '/api/academics/class-sections': { mode: 'shared' },
  '/api/academics/class-sections/[id]/homeroom-teacher': { mode: 'shared' },
  '/api/academics/class-subjects': { mode: 'shared' },
  '/api/academics/class-teachers': { mode: 'own', column: 'classes.branchId (via class_sections.classId)' },
  '/api/academics/classes': { mode: 'own', column: 'classes.branchId (via class_sections.classId)' },
  '/api/academics/classes/roster': { mode: 'own', column: 'classes.branchId (via class_sections.classId)' },
  '/api/academics/coverage': { mode: 'shared' },
  '/api/academics/elective-choices': { mode: 'shared' },
  '/api/academics/elective-groups': { mode: 'shared' },
  '/api/academics/exam-halls': { mode: 'own', column: 'exam_halls.branchId' },
  // review: exam logistics keyed to halls; scoping deferred to exam-master service pass
  '/api/academics/exam-schedules': { mode: 'review', column: 'exam_halls.branchId', review: true },
  // review: exam logistics keyed to halls; scoping deferred to exam-master service pass
  '/api/academics/exam-schedules/staff': { mode: 'review', column: 'exam_halls.branchId', review: true },
  '/api/academics/exam-terms': { mode: 'shared' },
  '/api/academics/exam-terms/[id]/marksheet': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/exam-terms/[id]/rankings': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/exam-terms/[id]/seat-allocation': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/exam-terms/[id]/stage': { mode: 'shared' },
  '/api/academics/grade-entry': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/grading-policies': { mode: 'shared' },
  '/api/academics/homework': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/homework/[id]': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/homework/[id]/attempts': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/homework/[id]/grade': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/homework/[id]/submit': { mode: 'personal' },
  '/api/academics/homework/upload': { mode: 'personal' },
  '/api/academics/massar/export/marksheet': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/massar/export/preview': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/massar/export/roster': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/massar/import/marks': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/mediums': { mode: 'shared' },
  '/api/academics/meeting-slots': { mode: 'personal' },
  '/api/academics/meeting-slots/book': { mode: 'personal' },
  '/api/academics/online-exams': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/online-exams/[examId]/questions': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/online-exams/[examId]/questions/[questionId]': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/online-exams/[examId]/take': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/online-exams/[examId]/variants': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/academics/online-exams/submit': { mode: 'personal' },
  '/api/academics/promotions/capacity-check': { mode: 'shared' },
  '/api/academics/promotions/revert': { mode: 'shared' },
  '/api/academics/question-bank': { mode: 'shared' },
  '/api/academics/question-bank/[id]/copy-into-exam': { mode: 'shared' },
  '/api/academics/readiness': { mode: 'shared' },
  '/api/academics/readiness/export': { mode: 'shared' },
  '/api/academics/readiness/snapshots': { mode: 'shared' },
  '/api/academics/room-utilization': { mode: 'shared' },
  '/api/academics/rooms': { mode: 'shared' },
  '/api/academics/sections': { mode: 'shared' },
  '/api/academics/semesters': { mode: 'shared' },
  '/api/academics/session-years': { mode: 'shared' },
  '/api/academics/session-years/open': { mode: 'shared' },
  '/api/academics/shifts': { mode: 'shared' },
  '/api/academics/streams': { mode: 'shared' },
  '/api/academics/streams/coefficients': { mode: 'shared' },
  // review: owner ruled 2026-09-26 (assignments win): this ADMIN-facing assignment manager stays campus-locked (admins strict); the teacher-side gates (marksheet/online-exam/homework) get the assignment exemption as a follow-up
  '/api/academics/subject-teachers': { mode: 'review', column: 'classes.branchId (via class_sections.classId)', review: true },
  '/api/academics/subjects': { mode: 'shared' },
  '/api/academics/syllabus': { mode: 'shared' },
  '/api/academics/teacher-availability': { mode: 'personal' },
  '/api/academics/teacher-question-bank': { mode: 'shared' },
  '/api/academics/teacher-question-bank/[id]': { mode: 'shared' },
  '/api/academics/teacher-question-bank/seed': { mode: 'shared' },
  '/api/academics/timetable-conflicts': { mode: 'own', column: 'classes.branchId (via class_sections)' },
  '/api/academics/timetable-conflicts/resolve': { mode: 'own', column: 'classes.branchId (via class_sections)' },
  '/api/academics/timetable-slots': { mode: 'own', column: 'classes.branchId (via class_sections)' },
  '/api/academics/timetable-slots/copy': { mode: 'own', column: 'classes.branchId (via class_sections)' },
  '/api/academics/timetable-versions': { mode: 'shared' },
  '/api/academics/timetable-versions/generate': { mode: 'shared' },
  '/api/academics/timetable-versions/publish': { mode: 'shared' },
  '/api/accountant/me/approvals': { mode: 'personal' },
  '/api/accountant/me/cashier': { mode: 'personal' },
  '/api/accountant/me/home': { mode: 'personal' },
  '/api/accountant/me/office-accounting': { mode: 'personal' },
  '/api/accountant/me/receivables': { mode: 'personal' },
  '/api/addons/broadcast/automations': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/automations/[id]': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/automations/[id]/runs': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/automations/[id]/test': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/automations/[id]/toggle': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/automations/runs/[runId]/recipients': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]/approve': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]/cancel': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]/export': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]/preview': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]/recipients': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]/report': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/campaigns/[id]/schedule': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/connections': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/connections/[id]': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/connections/[id]/send-test': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/connections/[id]/test': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/consents': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/deliveries/[id]/events': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/deliveries/[id]/retry': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/segments': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/segments/[id]': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/segments/[id]/preview': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/suppressions': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/suppressions/[id]': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/templates': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/templates/[id]': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/templates/[id]/versions': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/templates/[id]/versions/[versionId]/publish': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/waha/qr': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/broadcast/worker/process': { mode: 'own', column: 'broadcast tables branchId' },
  '/api/addons/events': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/attachments': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/attachments/[attachmentId]': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/audiences': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/audiences/[ruleId]': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/cancel': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/communications': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/feed.ics': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/feedback': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/feedback/[feedbackId]': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/incidents': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/incidents/[incidentId]': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/occurrences': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/publish': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/registrations': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/tasks': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/tasks/[taskId]': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/venues': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/[id]/venues/[venueId]': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/calendar': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/occurrences/[id]/checkins': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/occurrences/[id]/waitlist': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/occurrences/[id]/waitlist/[waitlistId]/respond': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/registrations/[id]/cancel': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/reports': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/events/types': { mode: 'own', column: 'events tables branchId' },
  '/api/addons/hostel/allocations': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/[id]/check-in': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/[id]/check-out': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/[id]/events': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/[id]/transfer': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/bulk/commit': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/bulk/preview': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/commit': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/allocations/preview': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/applications': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/applications/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/applications/[id]/decision': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/beds': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/beds/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/beds/[id]/status': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/board': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/categories': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/categories/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/escalations': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/escalations/[id]/acknowledge': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/escalations/run': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/guardian/me': { mode: 'personal' },
  '/api/addons/hostel/hostels': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/hostels/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/leave-passes': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/leave-passes/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/leave-passes/[id]/return': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/policies': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/reports/allocations': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/reports/occupancy': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/resident/me': { mode: 'personal' },
  '/api/addons/hostel/resident/me/leave-requests': { mode: 'personal' },
  '/api/addons/hostel/roll-calls': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/roll-calls/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/roll-calls/[id]/close': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/roll-calls/[id]/entries': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/rooms': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/rooms/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/tonight': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/zones': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/hostel/zones/[id]': { mode: 'own', column: 'hostel tables branchId' },
  '/api/addons/inventory/adjustments': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/adjustments/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/categories': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/categories/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/export': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/issues': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/issues/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/issues/[id]/return': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/movements': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/overview': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/products': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/products/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/purchases': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/purchases/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/purchases/[id]/receive': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/purchases/[id]/reverse': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/purchases/suggestions': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/sales': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/sales/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/sales/[id]/reverse': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/stock': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/stock/reconcile': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/stores': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/stores/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/suppliers': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/suppliers/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/transfers': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/transfers/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/transfers/[id]/cancel': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/transfers/[id]/complete': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/units': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/inventory/units/[id]': { mode: 'own', column: 'inventory tables branchId' },
  '/api/addons/library/catalog': { mode: 'shared' },
  '/api/addons/library/catalog/[id]': { mode: 'shared' },
  '/api/addons/library/catalog/[id]/contributors': { mode: 'shared' },
  '/api/addons/library/catalog/[id]/subjects': { mode: 'shared' },
  '/api/addons/library/catalog/categories': { mode: 'shared' },
  '/api/addons/library/catalog/categories/[id]': { mode: 'shared' },
  '/api/addons/library/catalog/contributors': { mode: 'shared' },
  '/api/addons/library/catalog/contributors/[id]': { mode: 'shared' },
  '/api/addons/library/catalog/publishers': { mode: 'shared' },
  '/api/addons/library/catalog/publishers/[id]': { mode: 'shared' },
  '/api/addons/library/catalog/subjects': { mode: 'shared' },
  '/api/addons/library/catalog/subjects/[id]': { mode: 'shared' },
  '/api/addons/library/charges': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/charges/[id]/post': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/charges/[id]/waive': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/circulation/issue': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/circulation/loans': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/circulation/renew': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/circulation/return': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/closures': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/closures/[id]': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/copies': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/copies/[id]': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/copies/export': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/copies/import': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/editions': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/editions/[id]': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/holds': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/holds/[id]/cancel': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/me/charges': { mode: 'personal' },
  '/api/addons/library/me/children': { mode: 'personal' },
  '/api/addons/library/me/children/[studentId]/loans': { mode: 'personal' },
  '/api/addons/library/me/history': { mode: 'personal' },
  '/api/addons/library/me/holds': { mode: 'personal' },
  '/api/addons/library/me/home': { mode: 'personal' },
  '/api/addons/library/me/loans': { mode: 'personal' },
  '/api/addons/library/me/renew': { mode: 'personal' },
  '/api/addons/library/members': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/members/[id]': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/policies': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/policies/[id]': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/reports/circulation': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/reports/inventory': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/reports/overdue': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/reports/overview': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/stocktakes': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/stocktakes/[id]/adjustments': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/stocktakes/[id]/adjustments/apply': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/stocktakes/[id]/close': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/stocktakes/[id]/observations': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/transfers': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/library/transfers/[id]/transition': { mode: 'own', column: 'library tables branchId' },
  '/api/addons/live-classrooms/health': { mode: 'personal' },
  '/api/addons/live-classrooms/my-sessions': { mode: 'personal' },
  '/api/addons/live-classrooms/my-sessions/[id]/join': { mode: 'personal' },
  '/api/addons/live-classrooms/provider-profiles': { mode: 'shared' },
  '/api/addons/live-classrooms/provider-profiles/[id]': { mode: 'shared' },
  '/api/addons/live-classrooms/provider-profiles/[id]/test': { mode: 'shared' },
  '/api/addons/live-classrooms/reports/export': { mode: 'shared' },
  '/api/addons/live-classrooms/reports/overview': { mode: 'shared' },
  '/api/addons/live-classrooms/reports/sessions': { mode: 'shared' },
  '/api/addons/live-classrooms/sessions': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/attendance': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/end': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/join': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/materials': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/materials/[assetId]': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/post-attendance': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/reconcile': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/recordings': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/recordings/[recordingId]': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/redeem-join': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/start': { mode: 'personal' },
  '/api/addons/live-classrooms/sessions/[id]/sync': { mode: 'personal' },
  '/api/addons/live-classrooms/webhooks/[providerType]': { mode: 'platform' },
  '/api/addons/reporting/admin/console': { mode: 'shared' },
  '/api/addons/reporting/catalog': { mode: 'shared' },
  '/api/addons/reporting/favorites': { mode: 'personal' },
  '/api/addons/reporting/reports/[key]/preview': { mode: 'shared' },
  '/api/addons/reporting/reports/[key]/run': { mode: 'shared' },
  // review: report-run rows carry branch_id; service-layer filter deferred (reporting service pass)
  '/api/addons/reporting/runs': { mode: 'review', column: 'report_runs.branchId', review: true },
  // review: report-run rows carry branch_id; service-layer filter deferred (reporting service pass)
  '/api/addons/reporting/runs/[id]': { mode: 'review', column: 'report_runs.branchId', review: true },
  // review: report-run rows carry branch_id; service-layer filter deferred (reporting service pass)
  '/api/addons/reporting/runs/[id]/download': { mode: 'review', column: 'report_runs.branchId', review: true },
  // review: report-run rows carry branch_id; service-layer filter deferred (reporting service pass)
  '/api/addons/reporting/runs/recover': { mode: 'review', column: 'report_runs.branchId', review: true },
  '/api/addons/reporting/saved-views': { mode: 'personal' },
  // review: report schedules carry branch_id; service-layer filter deferred (reporting service pass)
  '/api/addons/reporting/schedules': { mode: 'review', column: 'report_schedules.branchId', review: true },
  // review: report schedules carry branch_id; service-layer filter deferred (reporting service pass)
  '/api/addons/reporting/schedules/[id]': { mode: 'review', column: 'report_schedules.branchId', review: true },
  '/api/admissions/inquiries': { mode: 'own', column: 'applicants.branchId' },
  '/api/admissions/inquiries/convert': { mode: 'own', column: 'applicants.branchId' },
  '/api/alumni/directory': { mode: 'shared' },
  '/api/alumni/me/events': { mode: 'personal' },
  '/api/alumni/me/events/[id]/rsvp': { mode: 'personal' },
  '/api/alumni/me/mentoring': { mode: 'personal' },
  '/api/alumni/me/preferences': { mode: 'personal' },
  '/api/alumni/me/profile': { mode: 'personal' },
  '/api/alumni/me/records': { mode: 'personal' },
  '/api/alumni/me/records/[id]/download': { mode: 'personal' },
  '/api/alumni/me/requests': { mode: 'personal' },
  '/api/alumni/mentoring': { mode: 'shared' },
  '/api/analytics': { mode: 'shared' },
  '/api/attendance': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/audit-summary': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/day': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/excuses': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/excuses/document': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/flags': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/flags/detail': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/flags/notes': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/heatmap': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/history': { mode: 'student', column: 'classes.branchId (via attendance.classSectionId)' },
  '/api/attendance/kiosk/current-session': { mode: 'personal' },
  '/api/attendance/onsite': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/qr/events': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/qr/events/export': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/qr/scanner-sessions': { mode: 'personal' },
  '/api/attendance/qr/scanner-sessions/[id]/close': { mode: 'personal' },
  '/api/attendance/qr/scanner-sessions/[id]/events': { mode: 'personal' },
  '/api/attendance/qr/verify-and-stage': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/registers': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/registers/late-complete': { mode: 'own', column: 'classes.branchId (via session occurrence)' },
  '/api/attendance/registers/reopen': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/attendance/session-exceptions': { mode: 'own', column: 'classes.branchId (via class_schedule_slots)' },
  '/api/attendance/summary': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/audit-logs': { mode: 'shared' },
  '/api/audit-logs/export': { mode: 'shared' },
  '/api/auth/[...all]': { mode: 'platform' },
  '/api/auth/me': { mode: 'platform' },
  '/api/auth/setup-account': { mode: 'platform' },
  '/api/cards/admit-seats': { mode: 'own', column: 'exam_halls.branchId' },
  '/api/cards/employees': { mode: 'employee', column: 'user.branchId (staff member)' },
  '/api/cards/issue': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/cards/issued': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/cards/issued/[id]/pdf': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/cards/issued/[id]/revoke': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/cards/jobs': { mode: 'shared' },
  '/api/cards/jobs/[id]': { mode: 'shared' },
  '/api/cards/jobs/[id]/process': { mode: 'shared' },
  '/api/cards/overview': { mode: 'shared' },
  '/api/cards/templates': { mode: 'shared' },
  '/api/cards/templates/[id]': { mode: 'shared' },
  '/api/cards/templates/[id]/versions': { mode: 'shared' },
  '/api/certificates/definitions': { mode: 'shared' },
  '/api/certificates/definitions/[id]': { mode: 'shared' },
  '/api/certificates/definitions/[id]/versions': { mode: 'shared' },
  '/api/certificates/issue': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/certificates/issued': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/certificates/issued/[id]': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/certificates/issued/[id]/pdf': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/certificates/issued/[id]/replace': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/certificates/issued/[id]/revoke': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/certificates/jobs': { mode: 'shared' },
  '/api/certificates/jobs/[id]': { mode: 'shared' },
  '/api/certificates/jobs/[id]/process': { mode: 'shared' },
  '/api/certificates/overview': { mode: 'shared' },
  '/api/certificates/recipients': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/certificates/requests': { mode: 'personal' },
  '/api/certificates/requests/[id]': { mode: 'personal' },
  '/api/certificates/settings': { mode: 'shared' },
  '/api/certificates/signatories': { mode: 'shared' },
  '/api/certificates/signatories/[id]': { mode: 'shared' },
  '/api/certificates/templates': { mode: 'shared' },
  '/api/certificates/templates/[id]': { mode: 'shared' },
  '/api/certificates/templates/[id]/versions': { mode: 'shared' },
  '/api/communication/announcements': { mode: 'own', column: 'communication_*.branchId' },
  '/api/communication/announcements/mark-read': { mode: 'own', column: 'communication_*.branchId' },
  '/api/communication/announcements/unread-count': { mode: 'own', column: 'communication_*.branchId' },
  '/api/communication/balance': { mode: 'own', column: 'communication_*.branchId' },
  '/api/communication/messages': { mode: 'own', column: 'communication_*.branchId' },
  '/api/communication/reminder-audience': { mode: 'own', column: 'communication_*.branchId' },
  '/api/communication/send': { mode: 'own', column: 'communication_*.branchId' },
  '/api/communication/templates': { mode: 'shared' },
  '/api/content/assets': { mode: 'own', column: 'files.branchId' },
  '/api/content/assets/[id]': { mode: 'own', column: 'files.branchId' },
  '/api/content/assets/[id]/archive': { mode: 'own', column: 'files.branchId' },
  '/api/content/assets/[id]/download': { mode: 'own', column: 'files.branchId' },
  '/api/content/assets/[id]/publish': { mode: 'own', column: 'files.branchId' },
  '/api/content/assets/[id]/targets': { mode: 'own', column: 'files.branchId' },
  '/api/content/assets/[id]/usage-links': { mode: 'own', column: 'files.branchId' },
  '/api/content/assets/[id]/versions': { mode: 'own', column: 'files.branchId' },
  '/api/content/attachment-types': { mode: 'shared' },
  '/api/content/attachment-types/[id]': { mode: 'shared' },
  '/api/crm/inquiries': { mode: 'own', column: 'leadership_scope_assignments.branchId' },
  '/api/crm/inquiries/[id]': { mode: 'own', column: 'leadership_scope_assignments.branchId' },
  '/api/crm/inquiries/[id]/duplicates': { mode: 'own', column: 'leadership_scope_assignments.branchId' },
  '/api/crm/inquiries/[id]/follow-ups': { mode: 'own', column: 'leadership_scope_assignments.branchId' },
  '/api/crm/inquiries/merge': { mode: 'own', column: 'leadership_scope_assignments.branchId' },
  '/api/dashboard/notifications': { mode: 'personal' },
  '/api/dashboard/summary': { mode: 'student', column: 'user.branchId / classes.branchId' },
  '/api/documents/artifacts/[id]': { mode: 'student', column: 'student_documents via studentId' },
  '/api/documents/designs/[kind]': { mode: 'shared' },
  '/api/documents/designs/[kind]/publish': { mode: 'shared' },
  '/api/documents/previews': { mode: 'student', column: 'student_documents via studentId' },
  '/api/employee/me/advances': { mode: 'personal' },
  '/api/employee/me/awards': { mode: 'personal' },
  '/api/employee/me/documents': { mode: 'personal' },
  '/api/employee/me/documents/[documentId]/download': { mode: 'personal' },
  '/api/employee/me/home': { mode: 'personal' },
  '/api/employee/me/leave': { mode: 'personal' },
  '/api/employee/me/leave/[id]/cancel': { mode: 'personal' },
  '/api/employee/me/payroll': { mode: 'personal' },
  '/api/employee/me/payroll/[payslipId]/download': { mode: 'personal' },
  '/api/employee/me/preferences': { mode: 'personal' },
  '/api/employee/me/profile': { mode: 'personal' },
  '/api/employee/me/requests': { mode: 'personal' },
  '/api/employee/me/time': { mode: 'personal' },
  '/api/exports': { mode: 'review', review: true },
  '/api/exports/[id]': { mode: 'review', review: true },
  '/api/exports/[id]/download': { mode: 'review', review: true },
  '/api/finance/accounting/accounts': { mode: 'shared' },
  '/api/finance/accounting/deposits': { mode: 'shared' },
  '/api/finance/accounting/expenses': { mode: 'shared' },
  '/api/finance/accounting/expenses/[id]/approve': { mode: 'shared' },
  '/api/finance/accounting/expenses/[id]/post': { mode: 'shared' },
  '/api/finance/accounting/expenses/[id]/reject': { mode: 'shared' },
  '/api/finance/accounting/expenses/[id]/submit': { mode: 'shared' },
  '/api/finance/accounting/journal-entries': { mode: 'shared' },
  '/api/finance/accounting/journals': { mode: 'shared' },
  '/api/finance/accounting/periods': { mode: 'shared' },
  '/api/finance/accounting/periods/[id]/close': { mode: 'shared' },
  '/api/finance/accounting/periods/[id]/reopen': { mode: 'shared' },
  '/api/finance/accounting/periods/[id]/reopen-requests': { mode: 'shared' },
  '/api/finance/accounting/periods/[id]/reopen-requests/[requestId]/decide': { mode: 'shared' },
  '/api/finance/accounting/posting-status': { mode: 'shared' },
  '/api/finance/accounting/statements/[type]': { mode: 'shared' },
  '/api/finance/accounting/statements/drill-down': { mode: 'shared' },
  '/api/finance/accounting/student-accounting/exceptions': { mode: 'shared' },
  '/api/finance/accounting/student-accounting/exceptions/[id]': { mode: 'shared' },
  '/api/finance/accounting/student-accounting/mappings': { mode: 'shared' },
  '/api/finance/accounting/student-accounting/mappings/[id]': { mode: 'shared' },
  '/api/finance/accounting/student-accounting/post': { mode: 'shared' },
  '/api/finance/accounting/student-accounting/reconcile': { mode: 'shared' },
  '/api/finance/accounting/transactions': { mode: 'shared' },
  '/api/finance/accounting/transactions/[id]': { mode: 'shared' },
  '/api/finance/accounting/transactions/[id]/reverse': { mode: 'shared' },
  '/api/finance/accounting/trial-balance': { mode: 'shared' },
  '/api/finance/accounting/voucher-types': { mode: 'shared' },
  '/api/finance/allocations': { mode: 'student', column: 'user.branchId via invoice studentId' },
  '/api/finance/bank-reconciliation': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/close': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/fee-interest': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/import': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/match': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/matches': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/matches/unmatch': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/merge': { mode: 'shared' },
  '/api/finance/bank-reconciliation/[id]/split': { mode: 'shared' },
  '/api/finance/cashier-sessions': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/cashier-sessions/[id]/close': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/cashier-sessions/[id]/reconcile': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/chart-of-accounts': { mode: 'shared' },
  '/api/finance/credit-notes': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/credits': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/expenses': { mode: 'shared' },
  '/api/finance/expenses/receipt': { mode: 'shared' },
  '/api/finance/exports/journal': { mode: 'shared' },
  '/api/finance/exports/journal/push': { mode: 'shared' },
  '/api/finance/fee-allocation': { mode: 'own', column: 'fee_allocation_runs.branchId' },
  '/api/finance/fee-allocations': { mode: 'own', column: 'fee_allocation_runs.branchId' },
  '/api/finance/fee-allocations/[id]': { mode: 'own', column: 'fee_allocation_runs.branchId' },
  '/api/finance/fee-allocations/[id]/approve': { mode: 'own', column: 'fee_allocation_runs.branchId' },
  '/api/finance/fee-allocations/[id]/cancel': { mode: 'own', column: 'fee_allocation_runs.branchId' },
  '/api/finance/fee-allocations/[id]/run': { mode: 'own', column: 'fee_allocation_runs.branchId' },
  '/api/finance/fee-allocations/preview': { mode: 'own', column: 'fee_allocation_runs.branchId' },
  '/api/finance/fee-assignments': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/fee-structure-versions': { mode: 'review', review: true },
  '/api/finance/fee-structures': { mode: 'own', column: 'fee_structures.branchId' },
  '/api/finance/fee-structures/[id]/versions': { mode: 'own', column: 'fee_structures.branchId' },
  '/api/finance/fee-types': { mode: 'shared' },
  '/api/finance/fine-assessments': { mode: 'review', review: true },
  '/api/finance/fine-policies': { mode: 'shared' },
  '/api/finance/fine-runs': { mode: 'review', review: true },
  '/api/finance/fiscal-periods/close': { mode: 'review', review: true },
  '/api/finance/invoice-events': { mode: 'review', review: true },
  '/api/finance/invoices': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/invoices/[id]/cancel': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/invoices/[id]/credit': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/invoices/[id]/issue': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/journals': { mode: 'shared' },
  '/api/finance/lookups': { mode: 'review', review: true },
  '/api/finance/payment-methods': { mode: 'shared' },
  '/api/finance/payment-reversals': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/payments': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/payments/[id]/reverse': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/payments/online': { mode: 'student', column: 'user.branchId via studentId' },
  // platform: unauthenticated gateway webhook — no user context exists; the
  // tenant comes from the signature-verified session, never from a browser.
  '/api/finance/payments/online/callback': { mode: 'platform' },
  '/api/finance/payments/sandbox': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/receipts': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/receipts/[id]': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/refunds': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/reminder-rules': { mode: 'review', review: true },
  '/api/finance/reminder-runs': { mode: 'review', review: true },
  '/api/finance/reminders': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/finance/reports': { mode: 'review', review: true },
  '/api/finance/statements': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/gate/credentials/verify': { mode: 'personal' },
  '/api/guard/assignments': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/assignments/[id]': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/emergency/[activationId]/acknowledge': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/emergency/[activationId]/end': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/emergency/activate': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/emergency/procedures': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/gates': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/gates/[id]': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/incidents': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/incidents/[id]': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/incidents/[id]/actions': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/incidents/[id]/attachments': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/incidents/[id]/attachments/[attachmentId]': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/kiosk-sessions': { mode: 'personal' },
  '/api/guard/kiosk-sessions/[id]/close': { mode: 'personal' },
  '/api/guard/kiosk-sessions/[id]/lock': { mode: 'personal' },
  '/api/guard/me/expected': { mode: 'personal' },
  '/api/guard/me/gate': { mode: 'personal' },
  '/api/guard/me/incidents': { mode: 'personal' },
  '/api/guard/me/shift': { mode: 'personal' },
  '/api/guard/pickup-authorizations': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/pickup-authorizations/[id]/cancel': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/pickups/release': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/scans': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/shifts': { mode: 'shared' },
  '/api/guard/shifts/[id]': { mode: 'shared' },
  '/api/guard/students/[id]/pickups': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/students/search': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/visitor-invitations': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/visitor-invitations/[id]/approve': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/visitor-invitations/[id]/reject': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/visits': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/visits/[id]/check-in': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/visits/[id]/check-out': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guard/visits/[id]/pass': { mode: 'own', column: 'guard_* .branchId' },
  '/api/guardian/link/accept': { mode: 'personal' },
  '/api/guardian/link/start': { mode: 'personal' },
  '/api/guardian/me': { mode: 'personal' },
  '/api/guardian/me/children': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/announcements': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/attendance': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/documents': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/excuses': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/excuses/[excuseId]/document': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/finance': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/homework': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/meetings': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/overview': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/requests': { mode: 'personal' },
  '/api/guardian/me/children/[relationshipId]/results': { mode: 'personal' },
  '/api/guardian/me/finance': { mode: 'personal' },
  '/api/guardian/me/home': { mode: 'personal' },
  '/api/guardian/me/messages': { mode: 'personal' },
  '/api/guardian/me/preferences': { mode: 'personal' },
  '/api/health': { mode: 'platform' },
  '/api/hr/access': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/departments': { mode: 'own', column: 'departments.branchId' },
  '/api/hr/departments/[id]': { mode: 'own', column: 'departments.branchId' },
  '/api/hr/designations': { mode: 'shared' },
  '/api/hr/designations/[id]': { mode: 'shared' },
  '/api/hr/employee-profiles': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]/documents': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]/documents/[documentId]': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]/history': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]/link-account': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]/offboard': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]/payroll-attendance': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/employees/[id]/reactivate': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/export': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/leave/balances': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/leave/categories': { mode: 'shared' },
  '/api/hr/leave/requests': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/leave/requests/[id]': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/me/self-service-eligibility': { mode: 'personal' },
  '/api/hr/overview': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/payroll/periods': { mode: 'shared' },
  '/api/hr/payroll/periods/[id]/calculate': { mode: 'shared' },
  '/api/hr/payroll/periods/[id]/lines': { mode: 'shared' },
  '/api/hr/payroll/periods/[id]/lock': { mode: 'shared' },
  '/api/hr/payslips': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/payslips/[id]': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/profile-edit-requests': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/salary-assignments': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/hr/salary-templates': { mode: 'shared' },
  // review: staff badges follow the staff campus; badge service filter deferred (staff-badge pass)
  '/api/identity-badges': { mode: 'review', column: 'user.branchId (staff subject)', review: true },
  // review: staff badges follow the staff campus; badge service filter deferred (staff-badge pass)
  '/api/identity-badges/[id]': { mode: 'review', column: 'user.branchId (staff subject)', review: true },
  // review: staff badges follow the staff campus; badge service filter deferred (staff-badge pass)
  '/api/identity-badges/[id]/replace': { mode: 'review', column: 'user.branchId (staff subject)', review: true },
  // review: staff badges follow the staff campus; badge service filter deferred (staff-badge pass)
  '/api/identity-badges/bulk-issue': { mode: 'review', column: 'user.branchId (staff subject)', review: true },
  '/api/leadership/admin/authorities': { mode: 'shared' },
  '/api/leadership/admin/scopes': { mode: 'shared' },
  '/api/leadership/me/approvals': { mode: 'personal' },
  '/api/leadership/me/exceptions': { mode: 'personal' },
  '/api/leadership/me/home': { mode: 'personal' },
  '/api/me/permissions': { mode: 'personal' },
  '/api/notifications': { mode: 'personal' },
  '/api/platform/caddy-ask': { mode: 'platform' },
  '/api/platform/edge-tenant-resolve': { mode: 'platform' },
  '/api/portal/activity': { mode: 'personal' },
  '/api/portal/branch': { mode: 'personal' },
  '/api/portal/home': { mode: 'personal' },
  '/api/portal/manifest': { mode: 'personal' },
  '/api/portal/me': { mode: 'personal' },
  '/api/portal/preferences': { mode: 'personal' },
  '/api/portal/role': { mode: 'personal' },
  '/api/portal/search': { mode: 'personal' },
  '/api/public/alumni-documents/verify': { mode: 'platform' },
  '/api/public/cards/verify': { mode: 'platform' },
  '/api/public/certificates/verify': { mode: 'platform' },
  '/api/public/events/[tenantSlug]': { mode: 'platform' },
  '/api/public/inquiries/[tenantSlug]': { mode: 'platform' },
  '/api/public/invitations/[token]': { mode: 'platform' },
  '/api/public/invitations/[token]/accept': { mode: 'platform' },
  '/api/public/signup': { mode: 'platform' },
  '/api/public/website/[tenantSlug]/images/[filename]': { mode: 'platform' },
  '/api/public/website/[tenantSlug]/logo': { mode: 'platform' },
  '/api/reception/appointments': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/appointments/[id]': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/appointments/[id]/cancel': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/appointments/[id]/check-in': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/appointments/[id]/complete': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/appointments/[id]/no-show': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/appointments/[id]/reschedule': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/gates': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/handoffs': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/handoffs/[id]/acknowledge': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/handoffs/[id]/cancel': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/handoffs/[id]/resolve': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/inquiries': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/inquiries/[id]/follow-ups': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/lookup': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/me/home': { mode: 'personal' },
  '/api/reception/pickups/authorizations': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/pickups/authorizations/[id]/cancel': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/pickups/release': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/pickups/students': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/pickups/students/[id]/pickups': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/staff': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/verifications': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/visitors': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/visitors/[id]/check-in': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/visitors/[id]/check-out': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/reception/visitors/[id]/pass': { mode: 'own', column: 'reception_appointments/reception_handoffs.branchId' },
  '/api/scanner-devices': { mode: 'own', column: 'scanner_devices.branchId' },
  '/api/scanner-devices/[id]': { mode: 'own', column: 'scanner_devices.branchId' },
  '/api/scanner-devices/pair': { mode: 'own', column: 'scanner_devices.branchId' },
  '/api/search': { mode: 'shared' },
  '/api/security/dashboard': { mode: 'shared' },
  '/api/security/sessions/[id]': { mode: 'shared' },
  '/api/settings': { mode: 'shared' },
  '/api/settings/access-reset': { mode: 'shared' },
  '/api/settings/addons': { mode: 'shared' },
  '/api/settings/addons/[id]': { mode: 'shared' },
  '/api/settings/branches': { mode: 'shared' },
  '/api/settings/branches/[id]': { mode: 'shared' },
  '/api/settings/catalog': { mode: 'shared' },
  '/api/settings/cndp-filing': { mode: 'shared' },
  '/api/settings/custom-fields': { mode: 'shared' },
  '/api/settings/custom-fields/[id]': { mode: 'shared' },
  '/api/settings/custom-fields/[id]/values': { mode: 'shared' },
  '/api/settings/data-export': { mode: 'shared' },
  '/api/settings/domains': { mode: 'shared' },
  '/api/settings/domains/[id]/verify': { mode: 'shared' },
  '/api/settings/drafts': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/drafts/[id]': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/drafts/[id]/approve': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/drafts/[id]/reject': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/invitations': { mode: 'shared' },
  '/api/settings/invitations/[id]': { mode: 'shared' },
  '/api/settings/jobs/[id]/trigger': { mode: 'shared' },
  '/api/settings/logo': { mode: 'shared' },
  '/api/settings/migration': { mode: 'shared' },
  '/api/settings/migration/tasks/[id]': { mode: 'shared' },
  '/api/settings/migration/template': { mode: 'shared' },
  '/api/settings/numbering': { mode: 'shared' },
  '/api/settings/numbering/[id]': { mode: 'shared' },
  '/api/settings/numbering/[id]/next': { mode: 'shared' },
  '/api/settings/numbering/[id]/preview': { mode: 'shared' },
  '/api/settings/permissions': { mode: 'shared' },
  '/api/settings/providers': { mode: 'shared' },
  '/api/settings/providers/[id]': { mode: 'shared' },
  '/api/settings/providers/[id]/test': { mode: 'shared' },
  '/api/settings/readiness': { mode: 'shared' },
  '/api/settings/scheduled-jobs': { mode: 'shared' },
  '/api/settings/scheduled-jobs/[id]': { mode: 'shared' },
  '/api/settings/scheduled-jobs/[id]/runs': { mode: 'shared' },
  '/api/settings/scheduled-jobs/[id]/toggle': { mode: 'shared' },
  '/api/settings/scheduled-jobs/[id]/trigger': { mode: 'shared' },
  '/api/settings/search': { mode: 'shared' },
  '/api/settings/security/login-events': { mode: 'shared' },
  '/api/settings/subscription': { mode: 'shared' },
  '/api/settings/subscription/renewal-request': { mode: 'shared' },
  '/api/settings/values': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/values/[key]': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/values/[key]/peek': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/values/[key]/rotate': { mode: 'own', column: 'setting_values.branchId' },
  '/api/settings/website/images': { mode: 'shared' },
  '/api/settings/website/menu-items': { mode: 'shared' },
  '/api/settings/website/menu-items/[id]': { mode: 'shared' },
  '/api/settings/website/news': { mode: 'shared' },
  '/api/settings/website/news/[id]': { mode: 'shared' },
  '/api/settings/website/pages': { mode: 'shared' },
  '/api/settings/website/pages/[pageType]': { mode: 'shared' },
  '/api/settings/website/theme': { mode: 'shared' },
  '/api/student/me/attendance': { mode: 'personal' },
  '/api/student/me/exams': { mode: 'personal' },
  '/api/student/me/home': { mode: 'personal' },
  '/api/student/me/homework': { mode: 'personal' },
  '/api/student/me/report-cards': { mode: 'personal' },
  '/api/student/me/report-cards/[id]/pdf': { mode: 'personal' },
  '/api/student/me/results': { mode: 'personal' },
  '/api/student/me/subjects': { mode: 'personal' },
  '/api/student/me/timetable': { mode: 'personal' },
  '/api/students': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/[id]/regenerate-access': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/[id]/reinstate-from-alumni': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/[id]/transfer': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/[id]/transition-to-alumni': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/admissions': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]/approve': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]/checklist': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]/comments': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]/documents/[docType]': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]/enroll': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]/interview': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/[id]/reject': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/admissions/documents': { mode: 'own', column: 'applicants.branchId' },
  '/api/students/alumni': { mode: 'shared' },
  '/api/students/alumni/[id]/documents': { mode: 'shared' },
  '/api/students/alumni/events': { mode: 'shared' },
  '/api/students/alumni/requests': { mode: 'shared' },
  '/api/students/alumni/requests/[id]/status': { mode: 'shared' },
  '/api/students/bulk-transition-to-alumni': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/documents': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/import': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/matricules': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/parents': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/parents/[id]': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/parents/[id]/activity': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/parents/[id]/payments': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/parents/link': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/photos': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/placements': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/placements/auto': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/promotions': { mode: 'shared' },
  '/api/students/promotions/preview': { mode: 'shared' },
  '/api/students/report-card': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/report-card/issue': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/students/report-card/templates': { mode: 'shared' },
  '/api/students/transfer-stats': { mode: 'shared' },
  '/api/students/transfers': { mode: 'student', column: 'user.branchId via studentId' },
  '/api/super-admin/addon-definitions': { mode: 'platform' },
  '/api/super-admin/alerts': { mode: 'platform' },
  '/api/super-admin/domains': { mode: 'platform' },
  '/api/super-admin/domains/[id]': { mode: 'platform' },
  '/api/super-admin/domains/[id]/verify': { mode: 'platform' },
  '/api/super-admin/entitlements': { mode: 'platform' },
  '/api/super-admin/health': { mode: 'platform' },
  '/api/super-admin/plan-limits': { mode: 'platform' },
  '/api/super-admin/plans': { mode: 'platform' },
  '/api/super-admin/plans/[planTier]': { mode: 'platform' },
  '/api/super-admin/plans/[planTier]/sync': { mode: 'platform' },
  '/api/super-admin/reports': { mode: 'platform' },
  '/api/super-admin/schools': { mode: 'platform' },
  '/api/super-admin/schools/[id]/branches': { mode: 'platform' },
  '/api/super-admin/schools/anonymize': { mode: 'platform' },
  '/api/super-admin/schools/backup': { mode: 'platform' },
  '/api/super-admin/sms': { mode: 'platform' },
  '/api/super-admin/subscriptions': { mode: 'platform' },
  '/api/super-admin/subscriptions/[schoolId]': { mode: 'platform' },
  '/api/super-admin/subscriptions/[schoolId]/license': { mode: 'platform' },
  '/api/super-admin/subscriptions/[schoolId]/payments/[paymentId]/decision': { mode: 'platform' },
  '/api/super-admin/summary': { mode: 'platform' },
  '/api/super-admin/support': { mode: 'platform' },
  '/api/super-admin/tenant-context': { mode: 'platform' },
  '/api/super-admin/waitlist': { mode: 'platform' },
  '/api/super-admin/waitlist/convert': { mode: 'platform' },
  '/api/support/upload': { mode: 'platform' },
  '/api/teacher/me/classes': { mode: 'personal' },
  '/api/teacher/me/current-lesson': { mode: 'personal' },
  '/api/teacher/me/home': { mode: 'personal' },
  '/api/teacher/me/timetable': { mode: 'personal' },
  '/api/teachers': { mode: 'employee', column: 'user.branchId (teacher)' },
  '/api/teachers/documents': { mode: 'employee', column: 'user.branchId (teacher)' },
  '/api/teachers/export': { mode: 'employee', column: 'user.branchId (teacher)' },
  '/api/teachers/import': { mode: 'employee', column: 'user.branchId (teacher)' },
  '/api/teachers/options': { mode: 'employee', column: 'user.branchId (teacher)' },
  '/api/teachers/photo': { mode: 'employee', column: 'user.branchId (teacher)' },
  '/api/tenant/billing/checkout-session': { mode: 'platform' },
  '/api/tenant/billing/portal-session': { mode: 'platform' },
  '/api/tenant/support': { mode: 'platform' },
  '/api/transport/allocations': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/allocations/[id]': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/drivers': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/incidents': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/policies': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/reports/export': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/reports/overview': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/rider-events': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/routes': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/routes/[id]': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/self-service/guardian': { mode: 'personal' },
  '/api/transport/self-service/student': { mode: 'personal' },
  '/api/transport/stops': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/stops/[id]': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/trips': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/trips/[id]/complete': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/trips/[id]/roster': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/trips/[id]/start': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/vehicles': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/transport/vehicles/[id]': { mode: 'own', column: 'transport_routes.branchId' },
  '/api/users': { mode: 'shared' },
  '/api/users/unlock': { mode: 'shared' },
  '/api/waitlist': { mode: 'platform' },
  '/api/webhooks/communication/[provider]': { mode: 'platform' },
  '/api/webhooks/stripe-platform': { mode: 'platform' },
  '/api/workforce/advances': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/workforce/awards': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/workforce/payroll/config': { mode: 'shared' },
  '/api/workforce/payroll/config/[resource]/[id]/action': { mode: 'shared' },
  '/api/workforce/payroll/payments': { mode: 'shared' },
  '/api/workforce/payroll/payments/[id]/action': { mode: 'shared' },
  '/api/workforce/payroll/payments/[id]/export': { mode: 'shared' },
  '/api/workforce/payroll/payslips': { mode: 'shared' },
  '/api/workforce/payroll/runs': { mode: 'shared' },
  '/api/workforce/payroll/runs/[id]': { mode: 'shared' },
  '/api/workforce/payroll/runs/[id]/action': { mode: 'shared' },
  '/api/workforce/punches': { mode: 'employee', column: 'employee_profiles.branchId' },
  '/api/workforce/punches/[id]': { mode: 'employee', column: 'user.branchId (employee)' },
};
